### ISSUE TITLE
Add Short Circuit card rules and NFC card mappings

### ISSUE THREAD

**Issue by AndrewJack** [mainthread-technology/short-circuit#1]
@sjparkinson has this on the old Trello board.

![Waiting](http://gifs.joelglovier.com/waiting/coming-to-america-waiting.gif)

**Comment by laithnurie** [comment]
I tried to access our trello but said only admin allowed to re-open it

**Comment by sjparkinson** [comment]
Trello board Droidcon Hack - https://trello.com/b/xSGcDl3y/droidcon-hack.

Might still be closed, I'll add the rules if I get time tonight.
